<template>
  <div>
    <div class="row justify-content-around">
      <div class="col-12">
        <img class="img text-center" width="50%" src="../../assets/SVG-Animation-404-Page.gif" alt>
      </div>
      <div class="col-6 text-center mt-5">
          <p>Lo sentimos pagina no encontrada porfavor dirijase al inicio</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style Scoped>
.img {
    margin-left: 330px;
  /* width: 50%;
  height: 50%; */
}
</style>
